### ISSUE TITLE
"Header must provide a Content-Length property."

### ISSUE THREAD

**Issue by Mosho1** [Microsoft/vscode-tslint#127]
I'm getting these errors whenever I edit a file.

vscode-tslint: 0.6.0
tslint: 4.0.1

extensionHost.ts:255 [Extension Host] Error: Header must provide a Content-Length property.
    at StreamMessageReader.onData (C:\Users\sharo\.vscode\extensions\eg2.tslint-0.6.0\node_modules\vscode-jsonrpc\lib\messageReader.js:179:27)
    at Socket.<anonymous> (C:\Users\sharo\.vscode\extensions\eg2.tslint-0.6.0\node_modules\vscode-jsonrpc\lib\messageReader.js:164:19)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at readableAddChunk (_stream_readable.js:176:18)
    at Socket.Readable.push (_stream_readable.js:134:10)
    at Pipe.onread (net.js:543:20)

**Comment by egamma** [comment]
@Mosho1 trying to narrow it down:
- do you run custom rules and some of the custom rules write stdout? can you share your `tslint.json` and the vscode settings related to tslint?
- is the behaviour specific to the tslint version? Can you reproduce it when you install tslint 3.15.0? (`npm install tslint@3.15.0`)

**Comment by egamma** [comment]
I experienced the problem as well and I've decided to switch from stdin/stdout to IPC as the transport this avoids the problem.

Commit: ff36bc8ef962568747acacbc311b9b9c94b66f1e
Published the extension with the fix as 0.6.3.
