### ISSUE TITLE
'Cannot read property 'AbstractRule' of undefined' while validating

### ISSUE THREAD

**Issue by chimon2000** [Microsoft/vscode-tslint#170]
I get this error in the Output when linting, but not when linting from the terminal

**Versions**
```
tsc --version && tslint --version

Version 2.2.0
4.5.0
```

**Error**
```
vscode-tslint: 'Cannot read property 'AbstractRule' of undefined' while validating: <project_path>/conversation-detail.component.ts stacktrace: TypeError: Cannot read property 'AbstractRule' of undefined
    at Object.<anonymous> (<project_path>/node_modules/tslint-eslint-rules/dist/rules/terIndentRule.js:48:13)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at loadRule (<project_path>/node_modules/tslint/lib/ruleLoader.js:65:26)
    at findRule (<project_path>/node_modules/tslint/lib/ruleLoader.js:46:20)
```

**Comment by chimon2000** [comment]
After uninstalling & reinstalling the plugin, this error went away. Closing
