### ISSUE TITLE
'null: Error: null' in devtools console

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-tslint#194]
VSCode Version 1.12.0-insider
Commit 740f6620234326925592c40d2ec858bd457f9f6c

TS lint 0.11.0

- git clone https://github.com/Microsoft/vscode-html-languageservice
- open folder in VSCode
- open the dev tools. Find the following exception:
```
null: Error: null
    at new ResponseError (/home/aeschli/.vscode-insiders/extensions/eg2.tslint-0.11.0/node_modules/vscode-jsonrpc/lib/messages.js:40:28)
    at handleResponse (/home/aeschli/.vscode-insiders/extensions/eg2.tslint-0.11.0/node_modules/vscode-jsonrpc/lib/main.js:305:48)
    at ChildProcess.callback (/home/aeschli/.vscode-insiders/extensions/eg2.tslint-0.11.0/node_modules/vscode-jsonrpc/lib/main.js:486:13)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at process.nextTick (internal/child_process.js:752:12)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

**Comment by ckbrehm11** [comment]
Same issue with TSLint 0.12.0

**Comment by egamma** [comment]
The output in the dev console is ugly, but the output in the tslint output window tells the user why tslint was disabled and the exception ignored. Could swallow the exception, but lower prio for now.

**Comment by egamma** [comment]
This error shows up when vscode-tslint installed, but tslint cannot be installed for this workspace neither locally from the workspace nor globally. Since the workspace has not `tslint.json` the assumption is that there is no linting desired for this workspace, therefore the exception isn't shown to the end user.

Fixing by improving the error message shown in the dev console to make it clear what happens.
