### ISSUE TITLE
getText of undefined error

### ISSUE THREAD

**Issue by jrieken** [Microsoft/vscode-tslint#22]
From time to time I see an error that tslint cannot read `getText` of undefined, my guess is a void document - detail to be provided...

**Comment by jrieken** [comment]
<img width="560" alt="screen shot 2016-01-11 at 17 16 07" src="https://cloud.githubusercontent.com/assets/1794099/12239030/0f5f3788-b887-11e5-96ac-0f5fe58a2f70.png">

That's all I get..

**Comment by jrieken** [comment]
more insights

```
vscode-tslint: 'Cannot read property 'getText' of undefined' while validating: file:///Users/jrieken/Code/vscode/src/vs/workbench/parts/files/browser/files.contribution.ts stacktrace: TypeError: Cannot read property 'getText' of undefined
    at NoStringLiteralWalker.visitElementAccessExpression (/Users/jrieken/Code/vscode/node_modules/tslint/lib/rules/noStringLiteralRule.js:27:36)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:281:22)
    at /Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:63
    at visitNode (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7409:20)
    at Object.forEachChild (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7587:24)
    at NoStringLiteralWalker.SyntaxWalker.walkChildren (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:12)
    at NoStringLiteralWalker.SyntaxWalker.visitExpressionStatement (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:78:14)
    at NoStringLiteralWalker.SyntaxWalker.visitNode (/Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:290:22)
    at /Users/jrieken/Code/vscode/node_modules/tslint/lib/language/walker/syntaxWalker.js:440:63
    at visitEachNode (/Users/jrieken/Code/vscode/node_modules/typescript/lib/typescript.js:7421:30)
```

**Comment by egamma** [comment]
Fixed by protecting against tslint exceptions.
ac3d16ee998d1f433d23f843bab8804be9372a2a
