### ISSUE TITLE
TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by aeschli** [Microsoft/vscode-tslint#24]
I see the following exception in the console with tslint 0.5.4 installed.
```
TypeError: Cannot read property 'id' of undefined: TypeError: Cannot read property 'id' of undefined
    at /home/martinae/.vscode/extensions/eg2.tslint-0.5.4/node_modules/vscode-languageclient/lib/main.js:268:29
    at Object.d [as _notify] (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:13439)
    at Object.__dirname.undefined.L.enter (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:16601)
    at __dirname.undefined.t.Class.define._run (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:18427)
    at __dirname.undefined.t.Class.define._completed (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:5:17868)
    at Object.d.handle (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:11:20229)
    at process.<anonymous> (/home/martinae/VSCode-linux-x64/resources/app/out/vs/workbench/node/pluginHostProcess.js:19:28565)
    at emitTwo (events.js:87:13)
    at process.emit (events.js:172:7)
    at handleMessage (internal/child_process.js:685:10)
```

**Comment by egamma** [comment]
Closing, failed to reproduce using the steps in #1956 using vscode-tsling 0.5.9.
