### ISSUE TITLE
autoFixOnSave doesn't apply under a certain resource-constrained condition

### ISSUE THREAD

**Issue by drosen0** [Microsoft/vscode-tslint#360]
- tslint Version: 5.10.0
- typescript Version: 2.8.3
- extension Version: 1.0.32
- vscode Version: 1.24.1
- macos Version: 10.13.4

Steps to Reproduce:

While the computer is CPU or I/O constrained because of running a build...
1. make a change to a large file
2. press Cmd+S
3. quickly make another change
4. press Cmd+S again

**Comment by egamma** [comment]
@drosen0 when this happens can you pls open the developer console (Help>Toggle Developer Tools  and switch to the Console tab) and see whether there is a message in the console.

**Comment by drosen0** [comment]
@egamma,
Yes, I'm getting this message in the devtool console:

```
log.ts:171
ERR Unexpected token, expected , (12:25): SyntaxError: Unexpected token, expected , (12:25)
	at Parser.pp$5.raise (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:4454:13)
	at Parser.pp.unexpected (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:1761:8)
	at Parser.pp.expect (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:1749:33)
	at Parser.pp$8.flowParseFunctionTypeParams (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5605:12)
	at Parser.pp$8.flowParsePrimaryType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5716:20)
	at Parser.pp$8.flowParsePostfixType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5778:19)
	at Parser.pp$8.flowParsePrefixType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5795:17)
	at Parser.pp$8.flowParseAnonFunctionWithoutParens (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5800:20)
	at Parser.pp$8.flowParseIntersectionType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5815:19)
	at Parser.pp$8.flowParseUnionType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5826:19)
	at Parser.pp$8.flowParseType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5837:19)
	at Parser.pp$8.flowParseTypeInitialiser (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:4988:19)
	at Parser.pp$8.flowParseObjectType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5492:29)
	at Parser.pp$8.flowParsePrimaryType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5660:19)
	at Parser.pp$8.flowParsePostfixType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5778:19)
	at Parser.pp$8.flowParsePrefixType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5795:17)
	at Parser.pp$8.flowParseAnonFunctionWithoutParens (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5800:20)
	at Parser.pp$8.flowParseIntersectionType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5815:19)
	at Parser.pp$8.flowParseUnionType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5826:19)
	at Parser.pp$8.flowParseType (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5837:19)
	at Parser.pp$8.flowParseTypeInitialiser (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:4988:19)
	at Parser.pp$8.flowParseTypeAlias (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5252:21)
	at Parser.parseExpressionStatement (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5927:25)
	at Parser.pp$1.parseStatement (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:1911:17)
	at Parser.parseStatement (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:5910:22)
	at Parser.pp$1.parseBlockBody (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:2268:21)
	at Parser.pp$1.parseTopLevel (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:1778:8)
	at Parser.parse (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:1673:17)
	at parse (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/babylon/lib/index.js:7305:37)
	at Snapshot.exports.getASTfor.file [as _parser] (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/jest-editor-support/build/parsers/babylon_parser.js:24:50)
	at Snapshot.getMetadata (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/node_modules/jest-editor-support/build/Snapshot.js:113:27)
	at SnapshotCodeLensProvider.provideCodeLenses (/Users/drosen3/.vscode/extensions/Orta.vscode-jest-2.8.0/out/src/SnapshotCodeLens/SnapshotCodeLensProvider.js:23:26)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:688:113
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:887
	at new n.Class.derive._oncancel (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:83:776)
	at Object.t.asWinJsPromise (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:103:850)
	at e.provideCodeLenses (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:688:67)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:702:529
	at e._withAdapter (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:701:385)
	at e.$provideCodeLenses (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:702:491)
	at e._doInvokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:832)
	at e._invokeHandler (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:636:550)
	at e._receiveRequest (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:631)
	at e._receiveOneMessage (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:635:400)
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:634:315
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:637:395
	at /Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:95:432
	at e.fire (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:96:764)
	at Socket.<anonymous> (/Applications/Visual Studio Code.app/Contents/Resources/app/out/vs/workbench/node/extensionHostProcess.js:154:338)
	at emitOne (events.js:96:13)
	at Socket.emit (events.js:191:7)
	at readableAddChunk (_stream_readable.js:178:18)
	at Socket.Readable.push (_stream_readable.js:136:10)
	at Pipe.onread (net.js:560:20)

log.ts:165
WARN Aborted format on save after 750ms
```

Looks like it might be caused by an extension I have installed?

**Comment by egamma** [comment]
The exception is from the https://marketplace.visualstudio.com/items?itemName=Orta.vscode-jest extension and I suggest you report the exception against this extension´s repository.

The relevant message for this issue is this one

> WARN Aborted format on save after 750ms

This means autofix on save is skipped as well. Code that runs on the willSave event blocks the event loop. To protect VS Code from bad behaving extensions that execute too long on willSave, the code will be aborted. With the setting `editor.formatOnSaveTimeout` you can increase the timeout and I suggest you try this. 

Since there is nothing I can do about this behaviour in vscode-tslint, I have to close this issue as an upstream issue.

**Comment by drosen0** [comment]
Thank you! I'll try experimenting with the timeout and will submit an issue with https://github.com/jest-community/vscode-jest based on my findings.
