### ISSUE TITLE
The tslint server crashed 5 times in the last 3 minutes. The server will not be restarted.

### ISSUE THREAD

**Issue by lslocum** [Microsoft/vscode-tslint#383]
- tslint Version: 1.0.36
- typescript Version: 2.6.2
- VS Code Version: 1.26.1
  Commit: 493869ee8e8a846b0855873886fc79d480d342de
  Date: 2018-08-16T18:38:57.434Z
  Electron: 2.0.5
  Chrome: 61.0.3163.100
  Node.js: 8.9.3
  V8: 6.1.534.41
  Architecture: x64

Steps to Reproduce:
1. Open VS Code and wait 15 seconds. The error message above it displayed. The following is in output window:

[Info  - 10:15:55 AM] Linter is running.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\lslocum\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Info  - 10:16:21 AM] Connection to server got closed. Server will restart.
[Info  - 10:16:21 AM] Linter has stopped.
[Info  - 10:16:22 AM] Linter is running.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\lslocum\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Info  - 10:16:25 AM] Connection to server got closed. Server will restart.
[Info  - 10:16:25 AM] Linter has stopped.
[Info  - 10:16:26 AM] Linter is running.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\lslocum\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Info  - 10:16:28 AM] Connection to server got closed. Server will restart.
[Info  - 10:16:28 AM] Linter has stopped.
[Info  - 10:16:29 AM] Linter is running.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\lslocum\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Info  - 10:16:31 AM] Connection to server got closed. Server will restart.
[Info  - 10:16:31 AM] Linter has stopped.
[Info  - 10:16:32 AM] Linter is running.
events.js:183
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Users\lslocum\AppData\Local\Programs\Microsoft VS Code\Code.exe ENOENT
    at _errnoException (util.js:1024:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:190:19)
    at onErrorNT (internal/child_process.js:372:16)
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
[Error - 10:16:34 AM] Connection to server got closed. Server will not be restarted.
[Info  - 10:16:34 AM] Linter has stopped.

Errors started occurring after I updated VS Code.

**Comment by egamma** [comment]
@lslocum I haven´t received other reports like this almost looks like a corrupt extension. Can you move .vscode\extensions\eg2.tslint somewhere else so that you do not loose and then you re-install tslint.

**Comment by lslocum** [comment]
I updated to version 1.0.38 this morning and it is working again. Thank you.

**Comment by egamma** [comment]
So I suspect the previews version was corrupted somehow.
