### ISSUE TITLE
Better error messaging 

### ISSUE THREAD

**Issue by shadowii** [Microsoft/vscode-tslint#49]
I just installed tslint and the vscode extension, but I'm getting a cryptic error:

`vscode-tslint: Cannot read tslint configuration - 'Unexpected token ﻿'`

If possible it would be helpful if it said what line the error was at (assuming Code lets you do this). Although in this particular situation I don't think it would help. I've tried clearing out the tslint.json file to just { } but I get the same error. 

On another note, what version of tslint can I install against? I see comments here talking about 3.7, but the extension page itself recommends 3.2.1. I'm currently using 3.8.x, but will try downgrading.

**Comment by egamma** [comment]
@shadowii the error message is coming from tslint and it is just surfaced by vscode. What error message do you get when you run tslint on the command line?

vscode tslint supports 3.7 and 3.8 you should not downgrade. I'll update the extension page.

**Comment by shadowii** [comment]
Looks like I should hit up the tslint folks. I'm getting the following: 
```
undefined:1
﻿{
^

SyntaxError: Unexpected token ﻿
    at Object.parse (native)
    at loadConfigurationFromPath (C:\Users\...\node_modules\tslint\lib\configuration.js:90:31)
    at Object.findConfiguration (C:\Users\...\node_modules\tslint\lib\configuration.js:45:12)
    at processFile (C:\Users\...\node_modules\tslint\lib\tslint-cli.js:111:41)
    at Array.forEach (native)
    at Object.<anonymous> (C:\Users\...\node_modules\tslint\lib\tslint-cli.js:128:41)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
```

It looks like [tslint doesn't like UTF8](https://github.com/palantir/tslint/issues/782).

Thanks for the help!
